/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sneaker_store.ui;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import sneaker_store.da.DataAccessObject;
import sneaker_store.da.Shoe;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Robert
 */
public class MainScreen extends javax.swing.JFrame {

    String imagePath = "";

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        initAppearance();
        addOrRemove.setSize(400,342);
        DataAccessObject dap = new DataAccessObject();
        ArrayList <Shoe> Shoelist = dap.showShoes();
        addOrRemove.setLocationRelativeTo(null);
    }
    
    public void initAppearance(){
        Object [] title = {"ID", "Name", "Stock",  "Price"};
        DataAccessObject dap = new DataAccessObject();
        ArrayList <Shoe> Shoelist = dap.showShoes();
        Object [] [] ObjShoe = new Object[Shoelist.size()][title.length];
        jPanel2.removeAll();
        for (int i = 0; i < Shoelist.size(); i++){
            Shoe shoes = Shoelist.get(i);
            ObjShoe[i][0] = shoes.getId();
            ObjShoe[i][1] = shoes.getName();
            ObjShoe[i][2] = shoes.getStock();
            ObjShoe[i][3] = shoes.getPrice();
            
            shoeComponent shoe = new shoeComponent();
            shoe.setShoeComponent(shoes.getName(), shoes.getPrice(), shoes.getStock(), shoes.getImagePath());
            Border blackline = BorderFactory.createLineBorder(Color.black, 1, true);
            shoe.setBorder(blackline);
            jPanel2.add(shoe);
            jPanel2.revalidate();
        }
        DefaultTableModel dtm = new DefaultTableModel(ObjShoe, title);
        jTable1.setModel(dtm);
        jScrollPane1.setViewportView(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addOrRemove = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        UploadButton = new javax.swing.JButton();
        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonAddOrRemove = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        addOrRemove.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Name");
        addOrRemove.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jLabel3.setText("Stock");
        addOrRemove.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel4.setText("Image Path");
        addOrRemove.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        addOrRemove.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 110, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        addOrRemove.getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 110, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        addOrRemove.getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 110, -1));

        addButton.setBackground(new java.awt.Color(204, 255, 204));
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        addOrRemove.getContentPane().add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        removeButton.setBackground(new java.awt.Color(255, 204, 204));
        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        addOrRemove.getContentPane().add(removeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));
        addOrRemove.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("←");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        addOrRemove.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        addOrRemove.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 160, -1));

        jLabel6.setText("Price");
        addOrRemove.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        UploadButton.setText("Upload");
        UploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadButtonActionPerformed(evt);
            }
        });
        addOrRemove.getContentPane().add(UploadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 80, -1));

        jFrame1.getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 490, 560));

        buttonAddOrRemove.setText("Add, Remove or Update");
        buttonAddOrRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddOrRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAddOrRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, -1, -1));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddOrRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddOrRemoveActionPerformed
        // TODO add your handling code here:
        addOrRemove.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonAddOrRemoveActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        DataAccessObject dao = new DataAccessObject();
        String name = jTextField2.getText();
        String result = dao.removeShoes(name);
        if (result.equals("True")){
            JOptionPane.showMessageDialog(null, "Successfully removed");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Failed to remove");
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        DataAccessObject dao = new DataAccessObject();
        String name = jTextField2.getText();
        int stock = Integer.valueOf(jTextField3.getText());
        double price = Double.valueOf(jTextField4.getText());
        String result = dao.newShoes(name, price, stock, imagePath);
        if (result.equals("True")){
		System.out.println(name);
		System.out.println(stock);
		System.out.println(price);
		System.out.println(imagePath);
            JOptionPane.showMessageDialog(null, "Successfully added");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Failed to add");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        addOrRemove.setVisible(false);
        this.setVisible(true);
        initAppearance();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setForeground( new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setForeground( new java.awt.Color(0,0,0));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DataAccessObject dao = new DataAccessObject();
        String name = jTextField2.getText();
        int stock = Integer.valueOf(jTextField3.getText());
        double price = Double.valueOf(jTextField4.getText());
        String result = dao.updateShoes(price, stock, imagePath, name);
        if (result.equals("True")){
            JOptionPane.showMessageDialog(null, "Successfully updated");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Failed to update");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

        private void UploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadButtonActionPerformed
                // TODO add your handling code here:
		if (evt.getSource()==UploadButton) {
			JFileChooser fileChooser = new JFileChooser();
			int response = fileChooser.showOpenDialog(null);

			if (response == JFileChooser.APPROVE_OPTION) {
				String file = new File(fileChooser.getSelectedFile().getAbsolutePath()).toString();
				imagePath = file;
			}
		}

        }//GEN-LAST:event_UploadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UploadButton;
    private javax.swing.JButton addButton;
    private javax.swing.JFrame addOrRemove;
    private javax.swing.JButton buttonAddOrRemove;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
