/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sneaker_store.ui;

import java.awt.Color;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.border.Border;

/**
 *
 * @author lapto
 */
public class shoeComponent extends javax.swing.JPanel {

    /**
     * Creates new form shoeComponent
     */
    public shoeComponent() {
        initComponents();
        
    }
    
    public void setShoeComponent (String shoeName, Double shoePrice, int shoeStock, String imgPath){
        shoeNameLabel.setText("Name: " + shoeName);
        shoePriceLabel.setText("Price: " + String.valueOf(shoePrice));
        shoeStockLabel.setText("Stock: " + String.valueOf(shoeStock));
        System.out.println(imgPath);
        ImageIcon image = new ImageIcon(imgPath);
        Image newImage = image.getImage().getScaledInstance(138, 135, Image.SCALE_DEFAULT);
        shoePicture.setIcon(new ImageIcon(newImage));
    };
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shoePicture = new javax.swing.JLabel();
        shoeNameLabel = new javax.swing.JLabel();
        shoePriceLabel = new javax.swing.JLabel();
        shoeStockLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(150, 225));

        shoePicture.setText("shoePicture");

        shoeNameLabel.setText("shoeName");

        shoePriceLabel.setText("shoePrice");

        shoeStockLabel.setText("shoeStock");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shoePicture, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shoeNameLabel)
                            .addComponent(shoePriceLabel)
                            .addComponent(shoeStockLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shoePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shoeNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shoePriceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shoeStockLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel shoeNameLabel;
    private javax.swing.JLabel shoePicture;
    private javax.swing.JLabel shoePriceLabel;
    private javax.swing.JLabel shoeStockLabel;
    // End of variables declaration//GEN-END:variables
}
